name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Production
      run: |
        ssh -o StrictHostKeyChecking=no "web1@161.35.133.86"
        cd /home/dev1/prod &&
        git pull origin main &&
        ./deploy.sh
        "
